package com.redhat.demos.buildentappin60min;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsuranceClaim implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String policyHolderName;
   @org.kie.api.definition.type.Label(value = "Email")
   private java.lang.String policyHolderEmail;
   @org.kie.api.definition.type.Label(value = "Phone")
   private java.lang.String policyHolderPhone;
   @org.kie.api.definition.type.Label(value = "Policy Number")
   private java.lang.String policyNumber;
   @org.kie.api.definition.type.Label(value = "License Number")
   private java.lang.String policyHolderDriversLicense;
   @org.kie.api.definition.type.Label(value = "Vehicle Year")
   private java.lang.Integer vehicleYear;
   @org.kie.api.definition.type.Label(value = "Vehicle Make")
   private java.lang.String vehicleMake;
   @org.kie.api.definition.type.Label(value = "Vehicle Model")
   private java.lang.String vehicleModel;
   @org.kie.api.definition.type.Label(value = "Vehicle Color")
   private java.lang.String vehicleColor;
   @org.kie.api.definition.type.Label(value = "Vehicle License Plate")
   private java.lang.String vehicleLicense;
   @org.kie.api.definition.type.Label(value = "Accident Date")
   private java.util.Date accidentDate;
   @org.kie.api.definition.type.Label(value = "Location")
   private java.lang.String accidentLocation;
   @org.kie.api.definition.type.Label(value = "Description")
   private java.lang.String accidentDescription;
   @org.kie.api.definition.type.Label(value = "Photo")
   private java.lang.String accidentPhoto;

   public InsuranceClaim()
   {
   }

   public java.lang.String getPolicyHolderName()
   {
      return this.policyHolderName;
   }

   public void setPolicyHolderName(java.lang.String policyHolderName)
   {
      this.policyHolderName = policyHolderName;
   }

   public java.lang.String getPolicyHolderEmail()
   {
      return this.policyHolderEmail;
   }

   public void setPolicyHolderEmail(java.lang.String policyHolderEmail)
   {
      this.policyHolderEmail = policyHolderEmail;
   }

   public java.lang.String getPolicyHolderPhone()
   {
      return this.policyHolderPhone;
   }

   public void setPolicyHolderPhone(java.lang.String policyHolderPhone)
   {
      this.policyHolderPhone = policyHolderPhone;
   }

   public java.lang.String getPolicyNumber()
   {
      return this.policyNumber;
   }

   public void setPolicyNumber(java.lang.String policyNumber)
   {
      this.policyNumber = policyNumber;
   }

   public java.lang.String getPolicyHolderDriversLicense()
   {
      return this.policyHolderDriversLicense;
   }

   public void setPolicyHolderDriversLicense(
         java.lang.String policyHolderDriversLicense)
   {
      this.policyHolderDriversLicense = policyHolderDriversLicense;
   }

   public java.lang.Integer getVehicleYear()
   {
      return this.vehicleYear;
   }

   public void setVehicleYear(java.lang.Integer vehicleYear)
   {
      this.vehicleYear = vehicleYear;
   }

   public java.lang.String getVehicleMake()
   {
      return this.vehicleMake;
   }

   public void setVehicleMake(java.lang.String vehicleMake)
   {
      this.vehicleMake = vehicleMake;
   }

   public java.lang.String getVehicleModel()
   {
      return this.vehicleModel;
   }

   public void setVehicleModel(java.lang.String vehicleModel)
   {
      this.vehicleModel = vehicleModel;
   }

   public java.lang.String getVehicleColor()
   {
      return this.vehicleColor;
   }

   public void setVehicleColor(java.lang.String vehicleColor)
   {
      this.vehicleColor = vehicleColor;
   }

   public java.lang.String getVehicleLicense()
   {
      return this.vehicleLicense;
   }

   public void setVehicleLicense(java.lang.String vehicleLicense)
   {
      this.vehicleLicense = vehicleLicense;
   }

   public java.util.Date getAccidentDate()
   {
      return this.accidentDate;
   }

   public void setAccidentDate(java.util.Date accidentDate)
   {
      this.accidentDate = accidentDate;
   }

   public java.lang.String getAccidentLocation()
   {
      return this.accidentLocation;
   }

   public void setAccidentLocation(java.lang.String accidentLocation)
   {
      this.accidentLocation = accidentLocation;
   }

   public java.lang.String getAccidentDescription()
   {
      return this.accidentDescription;
   }

   public void setAccidentDescription(java.lang.String accidentDescription)
   {
      this.accidentDescription = accidentDescription;
   }

   public java.lang.String getAccidentPhoto()
   {
      return this.accidentPhoto;
   }

   public void setAccidentPhoto(java.lang.String accidentPhoto)
   {
      this.accidentPhoto = accidentPhoto;
   }

   public InsuranceClaim(java.lang.String policyHolderName,
         java.lang.String policyHolderEmail,
         java.lang.String policyHolderPhone, java.lang.String policyNumber,
         java.lang.String policyHolderDriversLicense,
         java.lang.Integer vehicleYear, java.lang.String vehicleMake,
         java.lang.String vehicleModel, java.lang.String vehicleColor,
         java.lang.String vehicleLicense, java.util.Date accidentDate,
         java.lang.String accidentLocation,
         java.lang.String accidentDescription, java.lang.String accidentPhoto)
   {
      this.policyHolderName = policyHolderName;
      this.policyHolderEmail = policyHolderEmail;
      this.policyHolderPhone = policyHolderPhone;
      this.policyNumber = policyNumber;
      this.policyHolderDriversLicense = policyHolderDriversLicense;
      this.vehicleYear = vehicleYear;
      this.vehicleMake = vehicleMake;
      this.vehicleModel = vehicleModel;
      this.vehicleColor = vehicleColor;
      this.vehicleLicense = vehicleLicense;
      this.accidentDate = accidentDate;
      this.accidentLocation = accidentLocation;
      this.accidentDescription = accidentDescription;
      this.accidentPhoto = accidentPhoto;
   }

}