package com.redhat.demos.buildentappin60min;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsuranceClaim implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public InsuranceClaim() {
    }

}